// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FaceRecognition/ImageProto.proto

package xin.marico.facerecogition.vo;

public final class ImageProto {
  private ImageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Image)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Java的消息名不能和java_outer_classname重名。
     *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
     * </pre>
     *
     * <code>optional string personName = 1;</code>
     */
    String getPersonName();
    /**
     * <pre>
     *Java的消息名不能和java_outer_classname重名。
     *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
     * </pre>
     *
     * <code>optional string personName = 1;</code>
     */
    com.google.protobuf.ByteString
        getPersonNameBytes();

    /**
     * <code>repeated int32 data = 2;</code>
     */
    java.util.List<Integer> getDataList();
    /**
     * <code>repeated int32 data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated int32 data = 2;</code>
     */
    int getData(int index);

    /**
     * <code>optional int32 cols = 3;</code>
     */
    int getCols();

    /**
     * <code>optional int32 rows = 4;</code>
     */
    int getRows();
  }
  /**
   * Protobuf type {@code Image}
   */
  public  static final class Image extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Image)
      ImageOrBuilder {
    // Use Image.newBuilder() to construct.
    private Image(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Image() {
      personName_ = "";
      data_ = java.util.Collections.emptyList();
      cols_ = 0;
      rows_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Image(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              personName_ = s;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {

              cols_ = input.readInt32();
              break;
            }
            case 32: {

              rows_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImageProto.internal_static_Image_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImageProto.internal_static_Image_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Image.class, Builder.class);
    }

    private int bitField0_;
    public static final int PERSONNAME_FIELD_NUMBER = 1;
    private volatile Object personName_;
    /**
     * <pre>
     *Java的消息名不能和java_outer_classname重名。
     *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
     * </pre>
     *
     * <code>optional string personName = 1;</code>
     */
    public String getPersonName() {
      Object ref = personName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        personName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Java的消息名不能和java_outer_classname重名。
     *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
     * </pre>
     *
     * <code>optional string personName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPersonNameBytes() {
      Object ref = personName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        personName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<Integer> data_;
    /**
     * <code>repeated int32 data = 2;</code>
     */
    public java.util.List<Integer>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated int32 data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated int32 data = 2;</code>
     */
    public int getData(int index) {
      return data_.get(index);
    }
    private int dataMemoizedSerializedSize = -1;

    public static final int COLS_FIELD_NUMBER = 3;
    private int cols_;
    /**
     * <code>optional int32 cols = 3;</code>
     */
    public int getCols() {
      return cols_;
    }

    public static final int ROWS_FIELD_NUMBER = 4;
    private int rows_;
    /**
     * <code>optional int32 rows = 4;</code>
     */
    public int getRows() {
      return rows_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getPersonNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, personName_);
      }
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeInt32NoTag(data_.get(i));
      }
      if (cols_ != 0) {
        output.writeInt32(3, cols_);
      }
      if (rows_ != 0) {
        output.writeInt32(4, rows_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPersonNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, personName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(data_.get(i));
        }
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      if (cols_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cols_);
      }
      if (rows_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rows_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Image)) {
        return super.equals(obj);
      }
      Image other = (Image) obj;

      boolean result = true;
      result = result && getPersonName()
          .equals(other.getPersonName());
      result = result && getDataList()
          .equals(other.getDataList());
      result = result && (getCols()
          == other.getCols());
      result = result && (getRows()
          == other.getRows());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PERSONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPersonName().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (37 * hash) + COLS_FIELD_NUMBER;
      hash = (53 * hash) + getCols();
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRows();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Image parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Image parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Image parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Image parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Image parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Image parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Image parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Image parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Image parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Image parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Image prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Image}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Image)
        ImageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImageProto.internal_static_Image_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImageProto.internal_static_Image_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Image.class, Builder.class);
      }

      // Construct using xin.marico.facerecogition.vo.ImageProto.Image.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        personName_ = "";

        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        cols_ = 0;

        rows_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImageProto.internal_static_Image_descriptor;
      }

      public Image getDefaultInstanceForType() {
        return Image.getDefaultInstance();
      }

      public Image build() {
        Image result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Image buildPartial() {
        Image result = new Image(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.personName_ = personName_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
        result.cols_ = cols_;
        result.rows_ = rows_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Image) {
          return mergeFrom((Image)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Image other) {
        if (other == Image.getDefaultInstance()) return this;
        if (!other.getPersonName().isEmpty()) {
          personName_ = other.personName_;
          onChanged();
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        if (other.getCols() != 0) {
          setCols(other.getCols());
        }
        if (other.getRows() != 0) {
          setRows(other.getRows());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Image parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Image) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object personName_ = "";
      /**
       * <pre>
       *Java的消息名不能和java_outer_classname重名。
       *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
       * </pre>
       *
       * <code>optional string personName = 1;</code>
       */
      public String getPersonName() {
        Object ref = personName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          personName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Java的消息名不能和java_outer_classname重名。
       *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
       * </pre>
       *
       * <code>optional string personName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPersonNameBytes() {
        Object ref = personName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          personName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Java的消息名不能和java_outer_classname重名。
       *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
       * </pre>
       *
       * <code>optional string personName = 1;</code>
       */
      public Builder setPersonName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Java的消息名不能和java_outer_classname重名。
       *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
       * </pre>
       *
       * <code>optional string personName = 1;</code>
       */
      public Builder clearPersonName() {
        
        personName_ = getDefaultInstance().getPersonName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Java的消息名不能和java_outer_classname重名。
       *cpp的生成的类名是根据消息名来的，所以要想生成类名为ImageProto的类，要将消息名在改成ImageProto
       * </pre>
       *
       * <code>optional string personName = 1;</code>
       */
      public Builder setPersonNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Integer> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<Integer>(data_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 data = 2;</code>
       */
      public java.util.List<Integer>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated int32 data = 2;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated int32 data = 2;</code>
       */
      public int getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated int32 data = 2;</code>
       */
      public Builder setData(
          int index, int value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 2;</code>
       */
      public Builder addData(int value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 2;</code>
       */
      public Builder addAllData(
          Iterable<? extends Integer> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 2;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int cols_ ;
      /**
       * <code>optional int32 cols = 3;</code>
       */
      public int getCols() {
        return cols_;
      }
      /**
       * <code>optional int32 cols = 3;</code>
       */
      public Builder setCols(int value) {
        
        cols_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cols = 3;</code>
       */
      public Builder clearCols() {
        
        cols_ = 0;
        onChanged();
        return this;
      }

      private int rows_ ;
      /**
       * <code>optional int32 rows = 4;</code>
       */
      public int getRows() {
        return rows_;
      }
      /**
       * <code>optional int32 rows = 4;</code>
       */
      public Builder setRows(int value) {
        
        rows_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rows = 4;</code>
       */
      public Builder clearRows() {
        
        rows_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Image)
    }

    // @@protoc_insertion_point(class_scope:Image)
    private static final Image DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Image();
    }

    public static Image getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Image>
        PARSER = new com.google.protobuf.AbstractParser<Image>() {
      public Image parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Image(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Image> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Image> getParserForType() {
      return PARSER;
    }

    public Image getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Image_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Image_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n FaceRecognition/ImageProto.proto\"E\n\005Im" +
      "age\022\022\n\npersonName\030\001 \001(\t\022\014\n\004data\030\002 \003(\005\022\014\n" +
      "\004cols\030\003 \001(\005\022\014\n\004rows\030\004 \001(\005B*\n\034xin.marico." +
      "facerecogition.voB\nImageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Image_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Image_descriptor,
        new String[] { "PersonName", "Data", "Cols", "Rows", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
