// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FaceRecognition/ResultProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ResultProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ResultProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ResultProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_FaceRecognition_2fResultProto_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_FaceRecognition_2fResultProto_2eproto() {
  protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FaceRecognition/ResultProto.proto");
  GOOGLE_CHECK(file != NULL);
  ResultProto_descriptor_ = file->message_type(0);
  static const int ResultProto_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ResultProto, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ResultProto, message_),
  };
  ResultProto_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ResultProto_descriptor_,
      ResultProto::internal_default_instance(),
      ResultProto_offsets_,
      -1,
      -1,
      -1,
      sizeof(ResultProto),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ResultProto, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FaceRecognition_2fResultProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ResultProto_descriptor_, ResultProto::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_FaceRecognition_2fResultProto_2eproto() {
  ResultProto_default_instance_.Shutdown();
  delete ResultProto_reflection_;
}

void protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  ResultProto_default_instance_.DefaultConstruct();
  ResultProto_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto_once_);
void protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto_once_,
                 &protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto_impl);
}
void protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!FaceRecognition/ResultProto.proto\".\n\013R"
    "esultProto\022\016\n\006status\030\001 \001(\005\022\017\n\007message\030\002 "
    "\001(\tB\"\n xin.marico.facerecogition.entityb"
    "\006proto3", 127);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FaceRecognition/ResultProto.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FaceRecognition_2fResultProto_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto_once_);
void protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto_once_,
                 &protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FaceRecognition_2fResultProto_2eproto {
  StaticDescriptorInitializer_FaceRecognition_2fResultProto_2eproto() {
    protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto();
  }
} static_descriptor_initializer_FaceRecognition_2fResultProto_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResultProto::kStatusFieldNumber;
const int ResultProto::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResultProto::ResultProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:ResultProto)
}

void ResultProto::InitAsDefaultInstance() {
}

ResultProto::ResultProto(const ResultProto& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ResultProto)
}

void ResultProto::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = 0;
  _cached_size_ = 0;
}

ResultProto::~ResultProto() {
  // @@protoc_insertion_point(destructor:ResultProto)
  SharedDtor();
}

void ResultProto::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ResultProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ResultProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ResultProto_descriptor_;
}

const ResultProto& ResultProto::default_instance() {
  protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<ResultProto> ResultProto_default_instance_;

ResultProto* ResultProto::New(::google::protobuf::Arena* arena) const {
  ResultProto* n = new ResultProto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ResultProto::Clear() {
// @@protoc_insertion_point(message_clear_start:ResultProto)
  status_ = 0;
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool ResultProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ResultProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 status = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_message;
        break;
      }

      // optional string message = 2;
      case 2: {
        if (tag == 18) {
         parse_message:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ResultProto.message"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ResultProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ResultProto)
  return false;
#undef DO_
}

void ResultProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ResultProto)
  // optional int32 status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->status(), output);
  }

  // optional string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ResultProto.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  // @@protoc_insertion_point(serialize_end:ResultProto)
}

::google::protobuf::uint8* ResultProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ResultProto)
  // optional int32 status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->status(), target);
  }

  // optional string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ResultProto.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ResultProto)
  return target;
}

size_t ResultProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResultProto)
  size_t total_size = 0;

  // optional int32 status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status());
  }

  // optional string message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ResultProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ResultProto)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ResultProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResultProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ResultProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ResultProto)
    UnsafeMergeFrom(*source);
  }
}

void ResultProto::MergeFrom(const ResultProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ResultProto)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void ResultProto::UnsafeMergeFrom(const ResultProto& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.status() != 0) {
    set_status(from.status());
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void ResultProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ResultProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResultProto::CopyFrom(const ResultProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResultProto)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool ResultProto::IsInitialized() const {

  return true;
}

void ResultProto::Swap(ResultProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResultProto::InternalSwap(ResultProto* other) {
  std::swap(status_, other->status_);
  message_.Swap(&other->message_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ResultProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ResultProto_descriptor_;
  metadata.reflection = ResultProto_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ResultProto

// optional int32 status = 1;
void ResultProto::clear_status() {
  status_ = 0;
}
::google::protobuf::int32 ResultProto::status() const {
  // @@protoc_insertion_point(field_get:ResultProto.status)
  return status_;
}
void ResultProto::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:ResultProto.status)
}

// optional string message = 2;
void ResultProto::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ResultProto::message() const {
  // @@protoc_insertion_point(field_get:ResultProto.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ResultProto::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ResultProto.message)
}
void ResultProto::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResultProto.message)
}
void ResultProto::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResultProto.message)
}
::std::string* ResultProto::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:ResultProto.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ResultProto::release_message() {
  // @@protoc_insertion_point(field_release:ResultProto.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ResultProto::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:ResultProto.message)
}

inline const ResultProto* ResultProto::internal_default_instance() {
  return &ResultProto_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
