// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FaceRecognition/ResultProto.proto
#define PROTOBUF_USE_DLLS

#ifndef PROTOBUF_FaceRecognition_2fResultProto_2eproto__INCLUDED
#define PROTOBUF_FaceRecognition_2fResultProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto();
void protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto();
void protobuf_AssignDesc_FaceRecognition_2fResultProto_2eproto();
void protobuf_ShutdownFile_FaceRecognition_2fResultProto_2eproto();

class ResultProto;

// ===================================================================

class ResultProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ResultProto) */ {
 public:
  ResultProto();
  virtual ~ResultProto();

  ResultProto(const ResultProto& from);

  inline ResultProto& operator=(const ResultProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultProto& default_instance();

  static const ResultProto* internal_default_instance();

  void Swap(ResultProto* other);

  // implements Message ----------------------------------------------

  inline ResultProto* New() const { return New(NULL); }

  ResultProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResultProto& from);
  void MergeFrom(const ResultProto& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResultProto* other);
  void UnsafeMergeFrom(const ResultProto& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // optional string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:ResultProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 status_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_FaceRecognition_2fResultProto_2eproto_impl();
  friend void  protobuf_AddDesc_FaceRecognition_2fResultProto_2eproto_impl();
  friend void protobuf_AssignDesc_FaceRecognition_2fResultProto_2eproto();
  friend void protobuf_ShutdownFile_FaceRecognition_2fResultProto_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<ResultProto> ResultProto_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ResultProto

// optional int32 status = 1;
inline void ResultProto::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 ResultProto::status() const {
  // @@protoc_insertion_point(field_get:ResultProto.status)
  return status_;
}
inline void ResultProto::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:ResultProto.status)
}

// optional string message = 2;
inline void ResultProto::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResultProto::message() const {
  // @@protoc_insertion_point(field_get:ResultProto.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResultProto::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ResultProto.message)
}
inline void ResultProto::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResultProto.message)
}
inline void ResultProto::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResultProto.message)
}
inline ::std::string* ResultProto::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:ResultProto.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResultProto::release_message() {
  // @@protoc_insertion_point(field_release:ResultProto.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResultProto::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:ResultProto.message)
}

inline const ResultProto* ResultProto::internal_default_instance() {
  return &ResultProto_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_FaceRecognition_2fResultProto_2eproto__INCLUDED
